import jaguarFPace from "./assets/images/popular_car1.png";
import toyotaCamry from "./assets/images/popular_car2.png";
import ferrariSF90 from "./assets/images/popular_car3.png";
import audiTT from "./assets/images/popular_car4.png";
import bMW440i from "./assets/images/popular_car5.png";

export const carsData = [
  {
    name: "Jaguar F PACE",
    engine: "1997 cc",
    mileage: "19.3 kmpl",
    body: "SUV",
    airConditioner: "yes",
    passengers: "5",
    fuel: "diesel",
    fuelCapacity: "60 Litres",
    transmission: "Automatic",
    img: jaguarFPace,
    price: "$50",
  },
  {
    name: "Toyota Camry",
    engine: "2487 cc",
    mileage: "19.2 kmpl",
    body: "Sedan",
    airConditioner: "yes",
    passengers: "5",
    fuel: "Petrol",
    fuelCapacity: "50 Litres",
    transmission: "Automatic",
    img: toyotaCamry,
    price: "$65",
  },
  {
    name: "Ferrari SF90",
    engine: "3990 cc",
    mileage: "18 kmpl",
    body: "Coupe",
    airConditioner: "yes",
    passengers: "2",
    fuel: "Petrol",
    fuelCapacity: "68 Litres",
    transmission: "Automatic",
    img: ferrariSF90,
    price: "$80",
  },
  {
    name: "Audi TT",
    engine: "1984 cc",
    mileage: "14.33 kmpl",
    body: "Coupe",
    airConditioner: "yes",
    passengers: "4",
    fuel: "Petrol",
    fuelCapacity: "55 Litres",
    transmission: "Automatic",
    img: audiTT,
    price: "$42",
  },
  {
    name: "BMW 440i",
    engine: "2979 cc",
    mileage: "14.03 kmpl",
    body: "Sedan",
    airConditioner: "yes",
    passengers: "4",
    fuel: "Petrol",
    fuelCapacity: "60 Litres",
    transmission: "Automatic",
    img: bMW440i,
    price: "$61",
  },
  // {
  //   name: 'Honda Clarity Fuel Cell',
  //   engine: '2979 cc',
  //   mileage: '14.03 kmpl',
  //   body: 'Sedan',
  //   airConditioner: 'yes',
  //   passengers: '5',
  //   fuel: 'Petrol',
  //   fuelCapacity: '60 Litres',
  //   transmission: 'Automatic',
  // },
];
