export const carData = [
  {
    name: 'Jaguar F PACE',
    engine: '1997 cc',
    mileage: '19.3 kmpl',
    body: 'SUV',
    airConditioner: 'yes',
    passengers: '5',
    fuel: 'diesel',
    fuelCapacity: '60 Litres',
    transmission: 'Automatic',
  },
  {
    name: 'Toyota Camry',
    engine: '2487 cc',
    mileage: '19.2 kmpl',
    body: 'Sedan',
    airConditioner: 'yes',
    passengers: '5',
    fuel: 'Petrol',
    fuelCapacity: '50 Litres',
    transmission: 'Automatic',
  },
  {
    name: 'Ferrari SF90',
    engine: '3990 cc',
    mileage: '18 kmpl',
    body: 'Coupe',
    airConditioner: 'yes',
    passengers: '2',
    fuel: 'Petrol',
    fuelCapacity: '68 Litres',
    transmission: 'Automatic',
  },
  {
    name: 'Audi TT',
    engine: '1984 cc',
    mileage: '14.33 kmpl',
    body: 'Coupe',
    airConditioner: 'yes',
    passengers: '4',
    fuel: 'Petrol',
    fuelCapacity: '55 Litres',
    transmission: 'Automatic',
  },
  {
    name: 'BMW 440i',
    engine: '2979 cc',
    mileage: '14.03 kmpl',
    body: 'Sedan',
    airConditioner: 'yes',
    passengers: '4',
    fuel: 'Petrol',
    fuelCapacity: '60 Litres',
    transmission: 'Automatic',
  },
  {
    name: 'Honda Clarity Fuel Cell',
    engine: '2979 cc',
    mileage: '14.03 kmpl',
    body: 'Sedan',
    airConditioner: 'yes',
    passengers: '5',
    fuel: 'Petrol',
    fuelCapacity: '60 Litres',
    transmission: 'Automatic',
  },
];
